apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kubernetes-deployment  # You can choose any name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-kubernetes-app  # Consistent label for the app
  template:
    metadata:
      labels:
        app: jenkins-kubernetes-app  # Consistent label for the app
    spec:
      containers:
      - name: hellodocker-container  # Name of the container (can be anything)
        image: jamesndubuisi/hellodocker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 82  # Your preferred port

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-kubernetes-service  # Name of the service
spec:
  selector:
    app: jenkins-kubernetes-app  # Match with the app label
  ports:
  - protocol: TCP
    port: 82  # Expose the same port as the container
    targetPort: 82
  type: NodePort
