apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kubernetes-cicd-pipeline  # You can choose any name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-kubernetes-pipeline-app  # Consistent label for the app
  template:
    metadata:
      labels:
        app: jenkins-kubernetes-pipeline-app  # Consistent label for the app
    spec:
      containers:
      - name: jenkins-kubernetes-pipeline-container  # Name of the container (can be anything)
        image: jamesndubuisi/hellodocker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080  # Update to port 8080 to match localhost access

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-kubernetes-pipeline-service  # Name of the service
spec:
  selector:
    app: jenkins-kubernetes-pipeline-app  # Match with the app label
  ports:
  - protocol: TCP
    port: 8080  # Expose port 8080
    targetPort: 8080  # Container listens on port 8080
    nodePort: 30080  # Map NodePort explicitly to 30080
  type: NodePort  # NodePort type allows external access
